language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - whoami
  - pwd
  - env
  - wget http://hughperkins.com/downloads/torch-install.tar.bz2
  - mkdir torch
  - cd torch
  - tar -xf ../torch-install.tar.bz2

script:
  - echo hello
  - source torch/install/torch-activate
  - env
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4

notifications:
  email:
    on_success: never
    on_failure: never


