language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - whoami
  - pwd
  - ls
  - git status
  - ls ~
  - echo $HOME
  - env
  - cd
  - git clone https://github.com/torch/distro.git ~/torch --recursive
  - cd ~/torch; ./install.sh >/dev/null
  - mkdir ~/git
  - cd ~/git
  - git clone https://github.com/hughperkins/cltorch.git ~/git/cltorch --recursive
  - cd ~/git/cltorch
  - source ~/torch/install/bin/torch-activate
  - luarocks make rocks/cltorch-scm-1.rockspec
  - cd ~/build/hughperkins/clnn

script:
  - echo hello
  - source ~/torch/install/bin/torch-activate
  - env
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4
  - luarocks make rocks/clnn-scm-1.rockspec
  - luajit -e 'require "clnn"'

notifications:
  email:
    on_success: never
    on_failure: never

